---
# Ansible playbook for a GitLab server.
#
# To do: Install postfix `yum -y install postfix`.
#

- hosts: 192.168.33.10
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - firewall
    - gitlab
